org: ${env:ORG_NAME}
service: ${env:SERVICE_NAME}

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: python3.13
  memorySize: 256
  stage: dev
  region: us-east-1
  timeout: 20
  iam:
    role: arn:aws:iam::${env:AWS_ACCOUNT_ID}:role/${env:ROLE_NAME}
  environment:
    INCIDENTS_TABLE: ${env:INCIDENTS_TABLE}
    USERS_TABLE: ${env:USERS_TABLE}
    SOCKET_TABLE: ${env:SOCKET_TABLE}
    JWT_SECRET: ${env:JWT_SECRET}
    JWT_EXPIRES_MINUTES: ${env:JWT_EXPIRES_MINUTES}
    WEBSOCKET_ENDPOINT: 
      Fn::Join:
        - ""
        - - "https://"
          - Ref: WebsocketsApi
          - ".execute-api."
          - Ref: AWS::Region
          - ".amazonaws.com/"
          - ${self:provider.stage}

functions:
  CrearIncidente:
    handler: lambdas/Incidentes/CrearIncidente.lambda_handler
    events:
      - http:
          path: /incidents/create
          method: post
          cors: true

  EditarIncidente:
    handler: lambdas/Incidentes/EditarIncidente.lambda_handler
    events:
      - http:
          path: /incidents/edit
          method: put
          cors: true

  ActualizarEstadoIncidente:
    handler: lambdas/Incidentes/ActualizarEstadoIncidente.lambda_handler
    events:
      - http:
          path: /incidents/update-status
          method: post
          cors: true

  BuscarIncidentesPorAlumno:
    handler: lambdas/Incidentes/BuscarIncidentesPorAlumno.lambda_handler
    events:
      - http:
          path: /incidents/by-student
          method: get
          cors: true

  BuscarIncidentesPorPiso:
    handler: lambdas/Incidentes/BuscarIncidentesPorPiso.lambda_handler
    events:
      - http:
          path: /incidents/by-floor
          method: get
          cors: true

  BuscarIncidentesPorUrgencia:
    handler: lambdas/Incidentes/BuscarIncidentesPorUrgencia.lambda_handler
    events:
      - http:
          path: /incidents/by-urgency
          method: get
          cors: true

  CrearUsuario:
    handler: lambdas/Usuarios/CrearUsuario.lambda_handler
    events:
      - http:
          path: /users/register
          method: post
          cors: true

  LoginUsuario:
    handler: lambdas/Usuarios/LoginUsuario.lambda_handler
    events:
      - http:
          path: /users/login
          method: post
          cors: true
  Connect:
    handler: WebSocket/connect.handler
    events:
      - websocket:
          route: $connect

  Disconnect:
    handler: WebSocket/disconnect.handler
    events:
      - websocket:  
          route: $disconnect

resources:
  Resources:

    TablaUsuarios:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USERS_TABLE}
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    IncidentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Incidents
        AttributeDefinitions:
          - AttributeName: incident_id
            AttributeType: S
          - AttributeName: student_id
            AttributeType: S
          - AttributeName: floor
            AttributeType: N
          - AttributeName: urgency
            AttributeType: S

        KeySchema:
          - AttributeName: incident_id
            KeyType: HASH

        BillingMode: PAY_PER_REQUEST

        GlobalSecondaryIndexes:

          # GSI por alumno
          - IndexName: IncidentsByStudent
            KeySchema:
              - AttributeName: student_id
                KeyType: HASH
            Projection:
              ProjectionType: ALL

          # GSI por piso
          - IndexName: IncidentsByFloor
            KeySchema:
              - AttributeName: floor
                KeyType: HASH
            Projection:
              ProjectionType: ALL

          # GSI por urgencia
          - IndexName: IncidentsByUrgency
            KeySchema:
              - AttributeName: urgency
                KeyType: HASH
            Projection:
              ProjectionType: ALL


    TablaConexionesWebSocket:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.SOCKET_TABLE}
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
