org: ${env:ORG_NAME}
service: ${env:SERVICE_NAME}

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: python3.13
  memorySize: 256
  timeout: 20
  iam:
    role: arn:aws:iam::${env:AWS_ACCOUNT_ID}:role/${env:ROLE_NAME}
  environment:
    USERS_TABLE: ${env:USERS_TABLE}
    SOCKET_TABLE: ${env:SOCKET_TABLE}
    JWT_SECRET: ${env:JWT_SECRET}
    JWT_EXPIRES_MINUTES: ${env:JWT_EXPIRES_MINUTES}
    WEBSOCKET_ENDPOINT: ${env:WEBSOCKET_ENDPOINT}
    
    USERS_TABLE: ${sls:stage}-t_usuarios
    JWT_SECRET: super-clave-ultra-secreta-123
    JWT_EXPIRES_MINUTES: 60
    INCIDENTS_TABLE: Incidents

functions:
  CrearUsuario:
    handler: lambdas/CrearUsuario.lambda_handler
    events:
      - http:
          path: /usuarios/register
          method: post
          cors: true

  LoginUsuario:
    handler: lambdas/LoginUsuario.lambda_handler
    events:
      - http:
          path: /usuarios/login
          method: post
          cors: true
  Connect:
    handler: websocket/connect.handler
    events:
      - websocket:
          route: $connect

  Disconnect:
    handler: websocket/disconnect.handler
    events:
      - websocket:
          route: $disconnect

resources:
  Resources:

    TablaUsuarios:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USERS_TABLE}
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    IncidentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Incidents
        AttributeDefinitions:
          - AttributeName: incident_id
            AttributeType: S
          - AttributeName: student_id
            AttributeType: S
          - AttributeName: floor
            AttributeType: N
          - AttributeName: urgency
            AttributeType: S

        KeySchema:
          - AttributeName: incident_id
            KeyType: HASH

        BillingMode: PAY_PER_REQUEST

        GlobalSecondaryIndexes:

          # GSI por alumno
          - IndexName: IncidentsByStudent
            KeySchema:
              - AttributeName: student_id
                KeyType: HASH
            Projection:
              ProjectionType: ALL

          # GSI por piso
          - IndexName: IncidentsByFloor
            KeySchema:
              - AttributeName: floor
                KeyType: HASH
            Projection:
              ProjectionType: ALL

          # GSI por urgencia
          - IndexName: IncidentsByUrgency
            KeySchema:
              - AttributeName: urgency
                KeyType: HASH
            Projection:
              ProjectionType: ALL


    TablaConexionesWebSocket:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.SOCKET_TABLE}
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST